import DoctorDetails from "../Screens/MainStack/DoctorDetails";

export const SCREENS = {
    ONBOARDING: 'Onboarding',
    WELCOME: 'Welcome',
    LOGIN: 'Login',
    SIGNUP: 'Signup',
    VERIFYCODE: 'VerifyCode',
    FORGET: 'Forget',
    RESETPASSWORD: 'ResetPassword',
    HOME: 'Home',
    FILTERS: 'Filters',
    MESSAGES: 'Messages',
    BOOKING: 'Booking',
    SEEALL: 'SeeALL',
    PROFILE: 'Profile',
    TERMSANDCONDITION: 'TermsAndCondition',
    DASHBOARD : 'dashboard',
    TABS: 'Tabs',
    SEEALLDOCTORS: 'SeeAllDoctors',
    DOCTORDETAILS: 'DoctorDetails',
    NEWAPPOINTMENT: 'NewAppointment',
    NOTIFICATONS: 'Notifications',
    CHAT: 'Chat',
    UPDATEPROFILE: 'UpdateProfile',
    FAVORITES: 'Favorites',
    HELPCENTER: 'HelpCenter',
    PAYMENTOPTION: 'PaymentOption',
    PASSWORDMANAGER: 'PasswordManager',
    NOTIFICATIONSETTINGS: 'NotificationsSettings',
    THEMESETTINGS: 'ThemeSettings',
    MYAPPOINTMENT: 'MyAppointment',
    CANCELAPPOINTMENT: 'CancelAppointment',
    ADDCARD: 'AddCard',
    REVIEWSUMMARY: 'ReviewSummary',
    PAYMENTSUCCESS: 'PaymentSuccess',

    

}